# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapedstories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedata',
            name='simage',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedata',
            name='slink',
            field=models.URLField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedata',
            name='snippet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedata',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
