# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-12 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapedstories', '0002_auto_20170112_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedUrlDefiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_url', models.URLField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
