# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapedstories', '0006_auto_20170115_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedata',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
