# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapedstories', '0007_auto_20170116_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedata',
            name='simage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedata',
            name='slink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
