# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-18 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapedstories', '0008_auto_20170116_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedata',
            name='category',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedata',
            name='simage',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedata',
            name='slink',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedata',
            name='title',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
