# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-07 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('written', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text=b'query here...')),
                ('written', models.DateTimeField()),
                ('user_posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soln_text', models.TextField()),
                ('soln_score', models.IntegerField(blank=True, null=True)),
                ('written', models.DateTimeField()),
                ('vote', models.IntegerField(default=0)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Query')),
                ('user_posted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='soln',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.Solutions'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_posted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
