# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-08 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_text',
            field=models.TextField(help_text='query here...'),
        ),
    ]
