# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-15 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_auto_20170108_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='disease',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
