# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0006_downvote_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='soln_num',
            field=models.IntegerField(default=0),
        ),
    ]
