# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-19 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='sentiment',
            field=models.CharField(blank=True, default=b'neutral', max_length=50, null=True),
        ),
    ]
