# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-24 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_auto_20170124_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templog',
            name='regno',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
