# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-21 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='userauth/static/userauth/images/profileimage.jpg', upload_to='uploads/images/'),
        ),
    ]
