# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-22 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_auto_20170121_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='title',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='consultation_location',
            field=models.CharField(blank=True, default='', max_length=125),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='reg_no',
            field=models.CharField(blank=True, max_length=125),
        ),
        migrations.AlterField(
            model_name='health_status',
            name='disease',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
