# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-24 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_auto_20170122_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
